services:
  frontend:
    image: ${DOCKERHUB_USERNAME}/boolock_client_${TYPE}:latest
    pull_policy: always
    ports:
      - '80:80'
      - '${SSL_PORT}'

  backend:
    image: ${DOCKERHUB_USERNAME}/boolock_server_${TYPE}:latest
    pull_policy: always
    ports:
      - '3000:3000'
