services:
  frontend:
    image: ${DOCKERHUB_USERNAME}/boolock_client_test:latest
    pull_policy: always
    ports:
      - '80:80'

  backend:
    image: ${DOCKERHUB_USERNAME}/boolock_server_test:latest
    pull_policy: always
    ports:
      - '3000:3000'
