services:
  frontend:
    build:
      image: ${DOCKERHUB_USERNAME}/boolock_client_test:latest
    ports:
      - '80:80'
      - '443:443'

  backend:
    build:
      image: ${DOCKERHUB_USERNAME}/boolock_server_test:latest
    ports:
      - '3000:3000'
