services:
  frontend:
    image: ${DOCKERHUB_USERNAME}/boolock_client_prod:latest
    pull_policy: always
    ports:
      - '80:80'
      - '443:443'

  backend:
    image: ${DOCKERHUB_USERNAME}/boolock_server_prod:latest
    pull_policy: always
    ports:
      - '3000:3000'
