name: main ci/cd action

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Set BE .env
        run: |
          echo "MONGO_URI=${{ secrets.DEPLOY_MONGO_URI }}"  > apps/server/.env
          echo "IS_LOCAL=false" >> apps/server/.env
          echo "SERVER_CORS_ACCEPT=${{ secrets.DEPLOY_SERVER_CORS_ACCEPT }}" >> apps/server/.env
          echo "S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }}" >> apps/server/.env
          echo "S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }}" >> apps/server/.env
          echo "S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}" >> apps/server/.env
          echo "NODE_ENV=production" >> apps/server/.env
      
      - name: Set FE .env
        run: |
          echo "VITE_SERVER_URL=${{ secrets.DEPLOY_VITE_SERVER_URL }}" > apps/client/.env
          echo "VITE_MIXPANEL_TOKEN=${{ secrets.VITE_MIXPANEL_TOKEN }}" >> apps/client/.env
          echo "VITE_STATIC_STORAGE_URL=${{ secrets.VITE_STATIC_STORAGE_URL }}" >> apps/client/.env

      - name: Set Nginx SSL files
        run: |
          mkdir -p apps/client/ssl
          echo "${{ secrets.SSL_FULLCHAIN }}" > apps/client/ssl/fullchain.pem
          echo "${{ secrets.SSL_PRIVKEY }}" > apps/client/ssl/privkey.pem

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and Push Base Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.base
          push: true 
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/base-image-prod:latest
          cache-from: type=gha,scope=base-image-prod
          cache-to: type=gha,mode=max,scope=base-image-prod

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: apps/client/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/boolock_client_prod:latest
          cache-from: type=gha,scope=frontend
          cache-to: type=gha,mode=max,scope=frontend
          build-args: |
            DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            TYPE=prod

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: apps/server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/boolock_server_prod:latest
          cache-from: type=gha,scope=backend
          cache-to: type=gha,mode=max,scope=backend
          build-args: |
            DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            TYPE=prod

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        run: |
          "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Deploy with docker
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd boolock/refactor-web31-BooLock
            git fetch origin
            git checkout main
            git pull origin main

            echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" > .env
            echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

            sudo docker compose pull
            sudo docker compose up -d --force-recreate --remove-orphans
